export type ServiceRequestRow = {
  id: string;
  client_id: string;
  title: string;
  description: string;
  category_id: string;
  subcategory_id: string;
  urgency: string;
  status: string;
  location_label: string | null;
  location_lat: number | null;
  location_lng: number | null;
  assigned_professional_id: string | null;
  photo_urls: string[];
  created_at: string;
  updated_at: string;
  category: { id: string; name: string; slug: string } | null;
  subcategory: { id: string; name: string; slug: string } | null;
  client: { id: string; full_name: string; avatar_url: string | null } | null;
};
