export const CLIENT_SERVICE_FEE_RATE = 0.05;

export const WORKER_SERVICE_FEE_RATE = 0.05;

export const CLIENT_SERVICE_FEE_PERCENT_LABEL = '5%';

export const WORKER_SERVICE_FEE_PERCENT_LABEL = '5%';

export const TOTAL_PLATFORM_FEE_RATE =
  CLIENT_SERVICE_FEE_RATE + WORKER_SERVICE_FEE_RATE;

export const TOTAL_PLATFORM_FEE_PERCENT_LABEL = '10%';
