const CATEGORY_ICONS: Record<string, string> = {
  home: '🏠',
  repairs: '🔧',
  services: '🛎️',
  care: '💙',
  other: '✨',
  transport: '🚚',
  beauty: '💇',
  education: '📚',
  events: '🎉',
};

const SUBCATEGORY_HINTS: Record<string, string> = {
  plumbing: 'Ej. Reparar fuga en el baño',
  electrical: 'Ej. Instalar tomas o arreglar cortocircuito',
  painting: 'Ej. Pintar habitación de 12 m²',
  cleaning: 'Ej. Limpieza profunda de apartamento',
  carpentry: 'Ej. Fabricar o reparar mueble de madera',
  gardening: 'Ej. Podar jardín o mantenimiento de plantas',
  masonry: 'Ej. Reparar muro o acabados en concreto',
  'ac-install': 'Ej. Instalar o mantener aire acondicionado',
  'home-organization': 'Ej. Organizar closet o espacios del hogar',
  general: 'Ej. Arreglar puerta o mueble',
  mechanical: 'Ej. Revisión o reparación de moto',
  locksmith: 'Ej. Abrir puerta o cambiar cerradura',
  appliances: 'Ej. Reparar nevera o lavadora',
  'computer-repair': 'Ej. Arreglar PC, celular o impresora',
  'gas-install': 'Ej. Instalar estufa o revisar instalación de gas',
  delivery: 'Ej. Mandado o entrega en la ciudad',
  cooking: 'Ej. Chef para cena en casa',
  errands: 'Ej. Trámites o compras por encargo',
  laundry: 'Ej. Lavado y planchado de ropa',
  'tech-support': 'Ej. Configurar Wi-Fi o resolver fallas',
  photography: 'Ej. Sesión de fotos o video corto',
  sewing: 'Ej. Arreglar pantalón o confección a medida',
  pets: 'Ej. Paseo o cuidado de mascota',
  babysitting: 'Ej. Cuidado de niños por la tarde',
  'elderly-care': 'Ej. Acompañamiento para adulto mayor',
  nursing: 'Ej. Cuidados básicos en casa',
  'pet-grooming': 'Ej. Baño y corte para mascota',
  'pet-training': 'Ej. Entrenamiento básico para perro',
  tutoring: 'Ej. Clases de matemáticas',
  languages: 'Ej. Clases de inglés a domicilio',
  'music-lessons': 'Ej. Clases de guitarra o piano',
  'sports-training': 'Ej. Entrenador personal en casa',
  'driving-lessons': 'Ej. Clases prácticas de conducción',
  moving: 'Ej. Mudanza de apartamento pequeño',
  'local-transport': 'Ej. Traslado dentro de la ciudad',
  courier: 'Ej. Entrega urgente de paquete',
  hairdressing: 'Ej. Corte y peinado a domicilio',
  makeup: 'Ej. Maquillaje para evento',
  barber: 'Ej. Corte de cabello y barba',
  nails: 'Ej. Manicure o pedicure en casa',
  'school-support': 'Ej. Refuerzo escolar en matemáticas',
  'exam-prep': 'Ej. Preparación para examen de admisión',
  'computer-skills': 'Ej. Clases de Excel o Word',
  'art-lessons': 'Ej. Clases de dibujo para niños',
  catering: 'Ej. Servicio de comida para fiesta',
  decoration: 'Ej. Decoración de cumpleaños',
  entertainment: 'Ej. DJ o animación para evento',
  other: 'Ej. Describe brevemente lo que necesitas',
};

export function getCategoryIcon(slug: string): string {
  return CATEGORY_ICONS[slug] ?? '📋';
}

export function getSubcategoryTitleHint(slug: string): string {
  return SUBCATEGORY_HINTS[slug] ?? 'Ej. Describe en pocas palabras lo que necesitas';
}
