export const SUBCATEGORY_KEYWORDS: Record<string, string[]> = {
  plumbing: [
    'plomeria',
    'plomero',
    'plomera',
    'fuga',
    'gotera',
    'tuberia',
    'cano',
    'caño',
    'grifo',
    'llave',
    'baño',
    'bano',
    'inodoro',
    'desague',
    'desagüe',
    'agua',
    'cisterna',
  ],
  electrical: [
    'electricidad',
    'electricista',
    'electrico',
    'luz',
    'luces',
    'enchufe',
    'tomacorriente',
    'cortocircuito',
    'cable',
    'cables',
    'interruptor',
    'breaker',
    'apagones',
  ],
  painting: ['pintura', 'pintor', 'pintar', 'pared', 'habitacion', 'habitación', 'brocha', 'rodillo'],
  cleaning: ['limpieza', 'limpiar', 'aseo', 'asear', 'casa', 'apartamento', 'oficina', 'domestico'],
  general: [
    'reparacion',
    'reparación',
    'arreglo',
    'arreglar',
    'puerta',
    'mueble',
    'gabinete',
    'perilla',
    'cerradura',
    'martillo',
  ],
  mechanical: ['mecanica', 'mecánica', 'mecanico', 'moto', 'motocicleta', 'auto', 'carro', 'vehiculo', 'motor'],
  delivery: ['delivery', 'mandado', 'mandados', 'envio', 'envío', 'recado', 'domicilio', 'entrega', 'mensajeria'],
  cooking: ['cocina', 'cocinar', 'chef', 'comida', 'cena', 'almuerzo', 'banquete', 'receta'],
  pets: ['mascota', 'mascotas', 'perro', 'perros', 'gato', 'gatos', 'paseo', 'pet', 'veterinaria'],
  babysitting: ['niños', 'ninos', 'niñera', 'ninera', 'cuidado infantil', 'bebe', 'bebé', 'guarderia'],
  tutoring: ['tutoria', 'tutoría', 'clases', 'clase', 'matematicas', 'matemáticas', 'estudio', 'profesor', 'escuela'],
  other: ['otro', 'otros', 'varios', 'general', 'servicio', 'ayuda'],
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  home: ['hogar', 'casa', 'domestico', 'doméstico', 'vivienda'],
  repairs: ['reparaciones', 'arreglos', 'fix', 'mantenimiento'],
  services: ['servicios', 'servicio', 'errands', 'mandados'],
  care: ['cuidado', 'cuidados', 'asistencia', 'ayuda personal'],
  other: ['otros', 'miscelaneo', 'misceláneo'],
};
